# Generated by Django 5.2.4 on 2025-08-29 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('walktrails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walktrail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='walktrails.walktrail')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '처리중'), ('completed', '완료'), ('rejected', '반려')], default='in_progress', max_length=20)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('response_image_url', models.URLField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_ReportStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_feedbacks', models.IntegerField(default=0)),
                ('type_counts', models.JSONField(default=dict)),
                ('type_ratios', models.JSONField(default=dict)),
                ('category_counts', models.JSONField(default=dict)),
                ('category_ratios', models.JSONField(default=dict)),
                ('completed_counts', models.IntegerField(default=0)),
                ('status_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walktrail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='walktrails.walktrail')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('walktrail', 'year', 'month')},
            },
        ),
    ]
