# Generated by Django 5.2.4 on 2025-08-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_func', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireport',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='monthly_reportstats',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='response',
            name='temp_field',
        ),
    ]
