# Generated by Django 5.2.4 on 2025-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_func', '0002_remove_aireport_temp_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_reportstats',
            name='type_ratios',
            field=models.JSONField(default=dict),
        ),
    ]
