# Generated by Django 5.2.4 on 2025-08-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_func', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response_image',
        ),
        migrations.AddField(
            model_name='response',
            name='response_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
