# Generated by Django 5.2.4 on 2025-08-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_func', '0003_remove_response_response_image_and_more'),
        ('walktrails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walktrail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='walktrails.walktrail')),
            ],
        ),
    ]
