# Generated by Django 5.2.4 on 2025-08-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='temp_field',
        ),
    ]
