# Generated by Django 5.2.4 on 2025-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ai_solution',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ai_importance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
