# Generated by Django 5.2.4 on 2025-07-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin',
        ),
    ]
