# Generated by Django 5.2.4 on 2025-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_ai_demand_feedback_ai_expected_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ai_importance',
            field=models.CharField(blank=True, null=True),
        ),
    ]
