# Generated by Django 5.2.4 on 2025-08-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_ai_demand_feedback_ai_expected_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="ai_note",),
    ]
