# Generated by Django 5.2.4 on 2025-07-31 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_id'),
        ('walktrails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='walktrail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='walktrails.walktrail'),
        ),
    ]
