# Generated by Django 5.2.4 on 2025-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_ai_expected_duration_feedback_ai_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ai_importance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
