# Generated by Django 5.2.4 on 2025-07-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_walktrail'),
        ('feedback', '0003_remove_feedback_admin'),
    ]

    operations = [
    ]
