# Generated by Django 5.2.4 on 2025-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_ai_importance"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="ai_solution",),
        migrations.AlterField(
            model_name="feedback",
            name="ai_demand",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
