# Generated by Django 5.2.4 on 2025-08-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_ai_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='temp_field',
        ),
    ]
