# Generated by Django 5.2.4 on 2025-08-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
