# Generated by Django 5.2.4 on 2025-07-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_merge_20250731_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response_content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response_image',
        ),
    ]
