# Generated by Django 5.2.4 on 2025-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_merge_20250731_1702'),
        ('feedback', '0005_remove_feedback_responded_at_and_more'),
    ]

    operations = [
    ]
