# Generated by Django 5.2.4 on 2025-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
