# Generated by Django 5.2.4 on 2025-08-29 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0003_remove_feedback_ai_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom_ai_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("style", models.CharField(max_length=100)),
                ("instruction", models.TextField()),
                ("report", models.JSONField(blank=True, null=True)),
                (
                    "docs_id",
                    models.ManyToManyField(
                        related_name="report", to="feedback.feedback"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
