# Generated by Django 5.2.4 on 2025-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom_ai_report",
            name="report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
