# Generated by Django 5.2.4 on 2025-08-23 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walktrails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_walktrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to=settings.AUTH_USER_MODEL)),
                ('walktrail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_policy', to='walktrails.walktrail')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'walktrail'), name='uniq_user_walktrail')],
            },
        ),
    ]
