# Generated by Django 5.2.4 on 2025-07-29 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인됨'), ('completed', '처리 완료'), ('rejected', '반려')], default='pending', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalkTrail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Walk Trail',
                'verbose_name_plural': 'Walk Trails',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', '승인'), ('reject', '반려'), ('assign', '담당자 지정'), ('completed', '완료')], max_length=20, verbose_name='조치')),
                ('content', models.TextField(verbose_name='응답 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='응답일')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='changetrail.admin', verbose_name='관리자')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='changetrail.feedback', verbose_name='피드백')),
            ],
            options={
                'verbose_name': '피드백 응답',
                'verbose_name_plural': '피드백 응답들',
                'db_table': 'feedback_response',
            },
        ),
        migrations.CreateModel(
            name='FeedbackApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=False, verbose_name='유효성 여부')),
                ('ai_message', models.TextField(blank=True, verbose_name='AI 분석 메시지')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='changetrail.feedback', verbose_name='피드백')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='changetrail.feedbackresponse', verbose_name='피드백 응답')),
            ],
            options={
                'verbose_name': '피드백 검증',
                'verbose_name_plural': '피드백 검증들',
                'db_table': 'feedback_approval',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='changetrail.user'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='changetrail.walktrail')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['trail', 'id'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='walk_trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='changetrail.walktrail'),
        ),
    ]
