# Generated by Django 5.2.4 on 2025-07-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changetrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nickname'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='walktrail',
            table='walk_trail',
        ),
    ]
