# Generated by Django 5.2.4 on 2025-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walktrails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walktrail',
            old_name='route_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='walktrail',
            old_name='distance',
            new_name='distance_km',
        ),
        migrations.RenameField(
            model_name='walktrail',
            old_name='time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
