# Generated by Django 5.2.4 on 2025-08-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walktrails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walktrail',
            name='created_at',
        ),
    ]
