# Generated by Django 5.2.4 on 2025-08-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walktrails', '0002_remove_walktrail_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AddField(
            model_name='walktrail',
            name='checkpoint',
            field=models.TextField(default=['성북천', '청계천', '전릉천', '세종대왕기념관', '홍릉근린공원', '영휘원-승인원']),
            preserve_default=False,
        ),
    ]
