# Generated by Django 5.2.4 on 2025-08-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walktrails', '0003_remove_route_name_walktrail_checkpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='longitude',
            new_name='lng',
        ),
    ]
